### PR TITLE
Map tutorial

### PR DESCRIPTION
**Pull request by Pablo-source**
This project is made  of a Quarto presentation and a revealjs Quarto presentation that I  have created in a new fork of the main project , following Trunc based development principles. Please let me know the steps I should follow to complete this pull request. we can review any piece of code if required

### CODE REVIEW

**Comment by Pablo-source** [comment]
Hi There, 

All the required materials used on the Maps in R presentation we did on the 26th of May 2023 NHS-R Drop in Session have been updated to this forked repo. And now I am requesting a pull request to go over the code review and subsequent merge when all checks are passed to merge it with the main branch. 

Forked from “nhsengland/nhs-r-reporting”. From there I have added my Maps presentation to the folder called /docs/tutorials

In that  that /tutorials folder, I have created a new folder containing the final Quarto presentation that we discussed on the 26th of May
/R_drop_in_session_26_may_Maps_in_R

In this newly created “R_drop_in_session_26_may_Maps_in_R” folder  I have included other two new sub-folders: 

1. Two new folders

1.1 Figures_map_slides folder
This folder includes the .png files used in the presentation. The folder name /Figures_maps_slides matches the path used in the slides, this will enable the .png  images to be displayed in the slides

1.2 data folder
This second folder contains the .xlsx file with the CCG indicators uses to populate the map and also another folder called “Clinical_Commissioning_Groups_April_2021” with all the required shapefile and polygon files required to draw the map boundaries, polygons and centroids. 
Finally both the Quarto presentation document “maps in R 26 May 2023.qmd” and rendered presentation .html file have been uploaded to the tutorials/R_drop_in_session_26_may_Maps_in_R newly created folder.
- maps in R 26 May 2023.qmd
- maps in R 26 May 2023.html

All the files used to create and output this Maps in R presentation haveb been uploaded to this pull request in GitHub. They include the final Quarto presentation, the shapefiles used to build the map and the .png files used to populated the screenshots in the final slide deck.

**Comment by aporter121** [comment]
Pablo - please add as single qmd file response that can run in the tutorials folder.

**Review by aporter121 — APPROVED** [review]
reviewing by deploying to live...

**Comment by aporter121** [comment]
Deploying to test.

**Pull request merged**
